# Out-of-tree build for the AES67 FPGA Ethernet + PHC (+ PCIe sound card) driver.
# Module name differs from every component object (Kbuild requirement).
obj-m += aes67_eth_drv.o
aes67_eth_drv-objs := aes67_eth.o aes67_bus.o aes67_phc.o

# Bus backends: spibone (SPI, Raspberry Pi) and PCIe (Alibaba KU3P card).
ifneq ($(CONFIG_SPI),)
aes67_eth_drv-objs += aes67_spi.o
endif
ifneq ($(CONFIG_PCI),)
aes67_eth_drv-objs += aes67_pci.o
ifneq ($(CONFIG_SND_PCM),)
aes67_eth_drv-objs += aes67_pcm.o
endif
endif
